module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "M_shahid 💚",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "private",
  "BOT_NUMBER": "94742274855",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "false",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "false",
  "ANTI_CALL": "false",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "94742274855",
  "ALWAYS_ONLINE": "false",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "M_Shahid 💚",
  "OWNER_NUMBER": "923318794921",
  "AUTO_BIO": "false",
  "AUTO_TYPING": "false",
  "AUTO_RECORDING": "false",
  "WARN_COUNT": "3",
  "AI_MODE": true,
};
